name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm ci
    - name: Cache .vscode-test
      uses: actions/cache@v3
      with:
        path: .vscode-test
        key: ${{ runner.os }}-test
    - run: xvfb-run -a npm test
      if: runner.os == 'Linux'
    - run: npm test
      if: runner.os != 'Linux'
    - name: Set nightly version
      run: |
        timestamp=$(date +%Y%m%d%H%M%S)
        version=$(npm pkg get version | sed 's/\"//g')
        npm pkg set version="$version-next+$timestamp"
      if: runner.os == 'Linux'
    - name: Create VSIX package
      run: npm run package -- --pre-release
      if: runner.os == 'Linux'
    - name: Upload VSIX package artifact
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v3
      with:
        name: vsix
        path: '*.vsix'
        retention-days: 1
